backend:
  replicaCount: 3

  image:
    repository: 378686993952.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: latest

frontend:
  replicaCount: 2

  image:
    tag: latest

ingress:
  host: employee.com