backend:
  replicaCount: 3

  image:
    repository: 378686993952.dkr.ecr.ap-south-1.amazonaws.com/backend
    tag: latest

  service:
    port: 5000

  env:
    port: "5000"
    dbHost: company-db-1.cle24u8cylpp.ap-south-1.rds.amazonaws.com
    dbPort: "5432"
    dbName: "postgres"
    dbSsl: "true"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  replicaCount: 2

  image:
    repository: saifali3366/employee-management-frontend
    tag: latest

  service:
    port: 80

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

    limits:
      cpu: "250m"
      memory: "256Mi"

postgres:
  replicaCount: 1

  image:
    repository: postgres
    tag: "16-alpine"

  service:
    port: 5432

  storage:
    claimName: postgres-pvc
    storageClass: gp2

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"

ingress:
  enabled: true
  host: employee.com

config:
  PORT: "5000"
  DB_HOST: "company-db-1.cle24u8cylpp.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "postgres"

secret:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "Emp!2026#RDS$SecurePg"
  POSTGRES_DB: "postgres"