postgres:
  replicaCount: 1

  image:
    repository: postgres
    tag: "16-alpine"

  service:
    port: 5432

  storage:
    claimName: postgres-pvc
    storageClass: gp2

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"