backend:
  replicaCount: 3

  image:
    repository: saifali3366/employee-management-backend
    tag: "new"

  service:
    port: 5000

  env:
    port: "5000"

    # Amazon RDS PostgreSQL
    dbHost: company-db-1.cle24u8cylpp.ap-south-1.rds.amazonaws.com
    dbPort: "5432"
    dbName: postgres

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"