apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.storage.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.storageClass }}
  resources:
    requests:
      storage: 5Gi