apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

type: Opaque

data:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | b64enc }}